version: '3.8'
services:
  frontend:
    build: 
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules


  backend:
    build: 
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
